spring:
  mvc:
    static-path-pattern: /**

  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.154.117/htd?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: work
    password: Yeweiqqiang007!
